#!/usr/bin/env python3
"""Shared first-use policy for source-facing AI Infra terminology.

Teaching prose keeps source/code spelling and explains it once when the course
first teaches the concept:

    shape（形状：表示 tensor 各维度的长度）
    scheduler（调度器：决定每轮哪些 requests 推进多少 token）

The parenthesis contains both the Chinese term and one concise beginner
explanation. Later uses keep the English/source spelling so the prose continues
to match code, profiler output, docs and repository identifiers.

Exact class/function/field/path identifiers are never translated internally.
"""

# term: (Chinese name, short beginner explanation)
SOURCE_TERMS = {
    # 01 · Foundations
    "PyTorch": ("深度学习框架", "本课程用它演示 tensor、自动求导和训练代码"),
    "tensor": ("张量", "多维数组，也是模型计算中最基本的数据对象"),
    "memory": ("内存", "保存数据、参数和中间状态的存储空间"),
    "shape": ("形状", "表示 tensor 各维度的长度"),
    "dtype": ("数据类型", "表示 tensor 元素用什么数值格式存储"),
    "device": ("设备位置", "表示数据位于 CPU 还是哪张 GPU"),
    "storage": ("底层存储", "真正承载 tensor 数据的内存区域"),
    "layout": ("内存布局", "描述逻辑元素怎样映射到底层 storage"),
    "stride": ("步长", "表示某一维索引增加 1 时底层地址跨多少元素"),
    "contiguous": ("连续存储", "表示数据是否按当前逻辑维度顺序紧密排列"),
    "view": ("视图", "在不复制数据时用另一种逻辑形状解释同一块 storage"),
    "reshape": ("重塑形状", "改变 tensor 的逻辑 shape，必要时可能发生数据重排"),
    "transpose": ("转置维度", "交换 tensor 的维度顺序而通常不立即复制数据"),
    "permute": ("维度重排", "改变 tensor 各维度的顺序"),
    "copy": ("复制", "真正生成或写入一份新的数据副本"),
    "Linear": ("线性层", "对输入做矩阵乘法，并可再加 bias"),
    "bias": ("偏置", "Linear 中加在矩阵乘法结果上的可学习参数"),
    "weight": ("权重", "Linear 等层中会被训练更新的矩阵参数"),
    "dot product": ("点积", "把两个同长度向量逐元素相乘后求和得到一个数字"),
    "concat": ("拼接", "把多个 tensor 沿指定维度接成一个更大的 tensor"),
    "loss": ("损失", "衡量模型预测与目标之间的误差"),
    "forward": ("前向计算", "用当前参数从输入计算模型输出和中间状态"),
    "backward": ("反向传播", "沿计算图反向计算参数 gradient"),
    "gradient": ("梯度", "表示 loss 对参数变化的敏感方向"),
    "parameter": ("参数", "训练中会被 optimizer 更新的可学习数值"),
    "optimizer": ("优化器", "根据 gradient 更新模型 parameter"),
    "optimizer state": ("优化器状态", "optimizer 为更新参数额外保存的历史量"),
    "activation": ("激活值", "forward 产生并可能在 backward 中复用的中间结果"),
    "activation checkpointing": ("激活值检查点", "不保存全部 activation，而在 backward 时重算以节省显存"),
    "autograd": ("自动求导", "PyTorch 自动记录计算图并计算 gradient 的机制"),
    "Adam": ("Adam 优化器", "利用一阶和二阶动量统计更新参数的常用 optimizer"),
    "gradient accumulation": ("梯度累积", "多个小批次的 gradient 先累加，再统一更新 parameter"),
    "checkpoint": ("检查点", "保存模型和训练状态，便于中断后继续训练"),
    "Data Parallel": ("数据并行", "不同 replica 处理不同数据，再同步训练状态"),

    # 02 · Transformer
    "Transformer": ("Transformer 模型", "现代大语言模型常用的基础网络结构"),
    "Attention": ("注意力机制", "让当前 token 按相关性读取上下文信息"),
    "token": ("词元", "模型处理文本时使用的离散序列单位"),
    "sequence": ("序列", "按顺序排列的一串 token"),
    "hidden dimension": ("隐藏维度", "每个 token 隐藏表示的向量宽度"),
    "projection": ("投影", "用线性变换把表示映射到新的特征空间"),
    "attention score": ("注意力分数", "衡量 Query 与 Key 相关性的数值"),
    "causal mask": ("因果掩码", "阻止当前位置读取未来 token"),
    "softmax": ("归一化函数", "把一组 scores 变成和为 1 的权重"),
    "attention head": ("注意力头", "在一个子空间中独立计算 Attention 的一路表示"),
    "output projection": ("输出投影", "把多头 Attention 结果重新映射回隐藏维度"),
    "KV Cache": ("KV 缓存", "保存历史 token 的 Key/Value，使生成时不必重复计算整段历史"),
    "KV Connector": ("KV 连接器", "在不同实例之间衔接和传递已有 KV state 的接口层"),
    "head dimension": ("每头维度", "每个 attention head 内部使用的向量宽度"),
    "FlashAttention": ("高效注意力实现", "通过重排 Attention 的计算与内存读写来降低显存 I/O"),
    "scaled dot-product attention": ("缩放点积注意力", "先缩放 Query-Key 点积，再用 softmax 得到 Attention 权重"),
    "LayerNorm": ("层归一化", "按特征维对单个样本的表示做归一化"),
    "RMSNorm": ("均方根归一化", "用均方根尺度归一化表示的常见方法"),
    "residual connection": ("残差连接", "把子层输入直接加回输出以稳定深层网络"),
    "Transformer block": ("Transformer 块", "由 Attention、MLP、Norm 和 residual 等子模块组成的一层计算单元"),
    "pre-norm": ("前置归一化", "先做 Norm 再进入 Attention 或 MLP 分支的结构"),
    "post-norm": ("后置归一化", "先完成子层和 residual 相加，再做 Norm 的结构"),
    "intermediate size": ("中间维度", "MLP 扩展后的隐藏表示宽度"),
    "gated MLP": ("门控 MLP", "用门控分支调制前馈输出的 MLP 变体"),
    "position encoding": ("位置编码", "把 token 在序列中的位置信息注入模型表示"),
    "runtime": ("运行时", "模型实际执行时负责组织计算、通信和数据状态的系统层"),
    "fused kernel": ("融合 kernel", "把多个操作合并到一次或更少 GPU kernel 中执行"),
    "KV reuse": ("KV 复用", "在语义兼容时直接使用已经计算好的 KV state"),
    "logits": ("未归一化分数", "模型在 softmax 前对候选 token 给出的原始分数"),
    "Context Parallel": ("上下文并行", "沿 sequence 或 context 维把长序列分给不同 GPU"),
    "Pipeline Parallel": ("流水线并行", "把不同 model layers 分给不同 GPU 阶段执行"),

    # 03 · GPU Systems
    "Tensor Core": ("张量核心", "NVIDIA GPU 中专门加速矩阵乘法的硬件单元"),
    "host memory": ("主机内存", "CPU 侧的系统内存"),
    "device memory": ("设备显存", "GPU 直接访问的本地设备内存"),
    "kernel": ("GPU 内核", "提交到 GPU 上执行的一段并行计算"),
    "stream": ("CUDA 流", "按顺序组织 GPU 异步工作的执行队列"),
    "compute-bound": ("计算受限", "性能主要受计算吞吐限制"),
    "memory-bound": ("内存带宽受限", "性能主要受数据读写带宽限制"),
    "communication-bound": ("通信受限", "性能主要受跨设备通信限制"),
    "arithmetic intensity": ("算术强度", "衡量每搬运 1 byte 数据能完成多少计算"),
    "Roofline": ("屋顶线模型", "把计算吞吐上限和内存带宽上限放在同一张图里比较"),
    "CUDA Graphs": ("CUDA 图", "把一组固定 GPU 工作预先记录后重复提交以减少 launch 开销"),
    "timeline": ("时间线", "按时间展示 CPU、GPU 和通信活动的性能视图"),
    "occupancy": ("占用率", "表示 GPU 执行资源上可驻留工作的利用程度"),
    "op": ("算子", "框架里一个可独立记录和执行的计算操作"),
    "copy engine": ("拷贝引擎", "GPU 中负责异步数据搬运的硬件引擎"),
    "InfiniBand": ("高性能网络互连", "数据中心常用的低延迟高带宽网络技术"),
    "Nsight Systems": ("系统性能分析器", "用 timeline 查看 CPU、GPU、CUDA 和通信活动"),
    "Nsight Compute": ("kernel 性能分析器", "下钻单个 GPU kernel 的计算、内存和占用率指标"),
    "PyTorch Profiler": ("PyTorch 性能分析器", "把框架算子与 CPU/CUDA 活动对应起来"),
    "bandwidth": ("带宽", "单位时间内链路能够传输的数据量"),
    "shared memory": ("共享内存", "同一线程块内线程可快速共享的片上存储"),
    "gradient reduce overlap": ("梯度归约重叠", "让 gradient 通信与后续计算并行"),
    "parameter gather overlap": ("参数收集重叠", "让 parameter gather 与计算并行"),
    "pipeline P2P overlap": ("流水线点对点重叠", "让 pipeline P2P 通信与计算并行"),
    "cuBLAS": ("CUDA 线性代数库", "NVIDIA 提供的 GPU 基础线性代数高性能库"),
    "CUTLASS": ("CUDA 模板线性代数库", "NVIDIA 提供的高性能矩阵乘与相关 kernel 模板库"),
    "Transformer Engine": ("Transformer 加速库", "NVIDIA 提供的 Transformer 低精度训练与推理加速库"),
    "launch overhead": ("启动开销", "提交 kernel 等工作本身带来的固定成本"),
    "profiler": ("性能分析器", "记录算子、时间线和资源使用情况的工具"),
    "buffer": ("缓冲区", "临时或持久保存待处理数据的一块内存"),
    "warp": ("线程束", "NVIDIA GPU 中一组按同一指令路径并行执行的线程"),
    "NVLink": ("GPU 高速互连", "NVIDIA GPU 之间常见的专用高带宽连接"),
    "NVSwitch": ("GPU 互连交换芯片", "把多条 NVLink 连接组织成更大规模 GPU 互连"),
    "workspace": ("工作区", "kernel 或 library 为一次计算临时申请的辅助内存"),
    "CUDA context": ("CUDA 上下文", "进程在 GPU 上执行时维护的运行环境与资源状态"),
    "allocator": ("内存分配器", "负责申请、缓存和复用内存块的组件"),
    "caching allocator": ("缓存分配器", "保留释放后的显存块以便后续快速复用的 allocator"),
    "nvidia-smi": ("NVIDIA GPU 状态工具", "查看 GPU、显存和进程状态的命令行工具"),
    "quantization": ("量化", "用更低精度表示权重或激活以降低存储和计算成本"),
    "offload": ("卸载", "把部分状态移到 CPU 或主机内存以降低 GPU 占用"),
    "concurrency": ("并发量", "系统同时保持活跃的 request 数量"),
    "Sequence Parallel": ("序列并行", "沿 sequence 维减少部分 activation 的重复存储与通信"),

    # 04 · Distributed
    "process": ("进程", "独立运行程序并拥有自己状态的执行实例"),
    "rank": ("进程编号", "分布式作业中标识一个 process 的编号"),
    "global rank": ("全局进程编号", "在整个分布式作业中唯一标识一个 process"),
    "local rank": ("本地进程编号", "标识 process 在当前机器上的本地序号"),
    "world size": ("总进程数", "表示当前 distributed world 中有多少个 processes"),
    "process group": ("进程组", "定义一组共同参与通信的 ranks"),
    "backend": ("后端", "提供具体通信或执行实现的一层接口"),
    "collective": ("集合通信", "一组 ranks 共同参与的数据通信操作"),
    "all-reduce": ("全归约", "归约各 rank 数据并把结果返回给所有参与者"),
    "all-gather": ("全收集", "收集各 rank 分片并让所有参与者得到完整结果"),
    "reduce-scatter": ("归约分散", "先归约再让每个 rank 只保留一份分片"),
    "broadcast": ("广播", "由一个 rank 把同一份数据发送给其它参与者"),
    "all-to-all": ("全交换", "每个 rank 都向其它 ranks 发送不同的数据分片"),
    "reduce": ("归约", "按 SUM、MAX 等规则把多个参与者的数据聚合起来"),
    "send": ("发送", "点对点通信中把 tensor 从当前 rank 发往另一个 rank"),
    "recv": ("接收", "点对点通信中从另一个 rank 接收 tensor"),
    "collective sequence": ("集合通信序列", "一个 rank 按时间依次执行 collective 的顺序记录"),
    "rendezvous": ("会合初始化", "让分布式 processes 发现彼此并建立通信所需信息"),
    "communicator": ("通信器", "通信库内部管理参与者与连接状态的对象"),
    "topology": ("拓扑", "描述 GPU、CPU、网络接口卡与网络之间的连接关系"),
    "torchrun": ("PyTorch 分布式启动器", "启动多个训练进程并为它们设置分布式身份信息"),
    "launcher": ("启动器", "负责创建分布式进程并传入必要启动配置的组件"),
    "distributed world": ("分布式参与者集合", "一次分布式作业中共同协作的全部 processes"),
    "default process group": ("默认进程组", "初始化后默认包含主要参与 ranks 的通信组"),
    "subgroup": ("子进程组", "从更大的 process group 中选出部分 ranks 形成的通信域"),
    "peer discovery": ("对端发现", "让分布式 processes 找到需要通信的其它参与者"),
    "membership": ("成员关系", "定义当前哪些 processes 属于同一个分布式通信集合"),
    "device mapping": ("设备映射", "决定某个 process 使用哪张本地 GPU 的对应关系"),
    "one-process-per-GPU": ("每 GPU 一进程", "每个 process 主要绑定一张 GPU 的常见部署方式"),
    "environment-variable initialization": ("环境变量初始化", "从 RANK、WORLD_SIZE 等环境变量读取进程组初始化信息"),
    "transport": ("传输后端", "负责底层设备或网络数据移动的实现层"),
    "NVLS": ("NVLink Sharp", "NCCL 在支持的平台上可选择的 NVLink/NVSwitch 集合通信加速算法族"),
    "GPUDirect RDMA": ("GPU 直连远程内存访问", "让网络设备更直接地读写 GPU memory，以减少 host memory 中转"),
    "message size": ("消息大小", "一次 collective 中每个 rank 需要参与传输的数据量"),
    "chunk": ("数据块", "把一个大 tensor 切出的较小传输单元"),
    "NIC": ("网络接口卡", "负责主机与外部网络之间收发数据的硬件设备"),
    "GPU/NIC affinity": ("亲和性", "描述 GPU 与 NIC 在硬件拓扑上的距离和访问关系"),
    "Ring": ("环形算法", "让各 rank 沿一个逻辑环与邻居分块交换数据"),
    "Tree": ("树形算法", "按层级聚合和分发数据，以减少通信阶段数"),
    "HPC": ("高性能计算", "面向大规模并行科学与工程计算的计算领域"),
    "DMA": ("直接内存访问", "设备在较少 CPU 搬运参与下直接读写内存的数据移动机制"),
    "IOMMU": ("输入输出内存管理单元", "为设备 DMA 提供地址转换和访问隔离的硬件单元"),
    "nccl-tests": ("NCCL 通信基准工具", "独立测量 NCCL collective 的延迟和带宽"),
    "MPI": ("消息传递接口", "HPC 中常见的进程间消息传递标准"),

    # 05 · Megatron
    "Megatron": ("大模型训练框架", "用于学习多维并行和分布式训练的源码实现"),
    "model parallelism": ("模型并行", "把单个模型的状态或计算显式拆到多张 GPU 上"),
    "parallel order": ("并行轴顺序", "决定不同并行维度如何映射到 ranks"),
    "Expert Parallel": ("专家并行", "把不同 MoE 专家分布到不同 ranks，简称 EP"),
    "Column Parallel": ("列并行", "沿 Linear 的输出维切分权重，让各 rank 计算不同输出特征"),
    "Row Parallel": ("行并行", "沿 Linear 的输入维切分权重，让各 rank 计算同一输出的部分贡献"),
    "RNG": ("随机数生成器", "dropout、初始化和采样等操作依赖的随机状态"),
    "autograd Function": ("自动求导函数", "把自定义 forward 与对应 backward 规则绑定起来的 PyTorch 抽象"),
    "dgrad": ("输入梯度", "loss 对某层输入 activation 的梯度"),
    "pipeline bubble": ("流水线气泡", "因为阶段依赖导致 GPU 暂时没有工作可做的空闲时间"),
    "1F1B": ("一次前向一次反向", "稳态中每个 pipeline stage 尽量交替执行一个 forward 和一个 backward microbatch"),
    "non-interleaved 1F1B": ("非交错 1F1B", "一个物理 rank 主要持有一个 pipeline stage"),
    "warmup": ("预热阶段", "先用 forward microbatches 逐步填满流水线"),
    "steady state": ("稳态阶段", "不同 stages 同时推进 forward 与 backward 工作"),
    "cooldown": ("排空阶段", "停止注入新的 forward 后完成剩余 backward"),
    "utilization": ("利用率", "有有效计算工作的时间占总执行时间的比例"),
    "interleaved schedule": ("交错调度", "让同一个物理 rank 持有多个模型块，并交替推进它们"),
    "model chunk": ("模型块", "交错流水线里分配给某个 rank 的一段模型层"),
    "virtual pipeline stage": ("虚拟流水线阶段", "在同一物理 rank 上进一步拆出的逻辑 stage"),
    "shard": ("分片", "把一份 tensor 或 state 拆成多份分到不同 ranks"),
    "replica": ("副本", "在不同 ranks 上保存的同一逻辑模型或 state"),
    "pipeline stage": ("流水线阶段", "负责模型连续一部分 layers 的执行阶段"),
    "microbatch": ("微批次", "把一个 batch 再切小以形成 Pipeline Parallel"),
    "bucket": ("通信桶", "把多块小数据合并后统一通信的分组单位"),
    "overlap": ("重叠执行", "让计算与通信并行以隐藏部分等待时间"),
    "expert": ("专家子网络", "MoE 中由 router 选择执行的稀疏前馈子网络"),
    "router": ("路由器", "根据规则决定 token 或 request 应被送往哪里"),
    "dispatcher": ("分发器", "按 routing 结果把 token 送到对应 expert 或目标"),
    "assignment": ("分配关系", "一次 token 到某个 expert 的 routing 记录"),

    # 06 · Inference
    "Prefill": ("预填充阶段", "一次处理 prompt 并建立历史 KV state 的阶段"),
    "Decode": ("解码阶段", "利用已有 KV state 一步步生成新 token 的阶段"),
    "prompt": ("输入提示", "送给模型作为生成上下文的输入 token 序列"),
    "request": ("请求", "一次进入推理服务并持续推进的生成任务"),
    "scheduler": ("调度器", "决定每轮哪些 requests 推进以及推进多少 token"),
    "iteration": ("执行轮次", "scheduler 规划并执行一次模型工作的循环"),
    "batch": ("批次", "一次共同送入模型执行的一组数据或 token 工作"),
    "continuous batching": ("连续批处理", "每个调度轮次都可以重新组成执行 batch"),
    "engine": ("推理引擎", "把 request 管理、scheduler 和模型执行组织成服务循环"),
    "workload": ("工作负载", "系统实际接收的一组 request 规模与分布特征"),
    "prefix cache": ("前缀缓存", "复用相同输入前缀已经计算好的 KV state"),
    "preemption": ("抢占", "资源不足时暂时移出正在运行的 request 并稍后恢复"),
    "throughput": ("吞吐量", "单位时间内系统完成的 request 或 token 数量"),
    "latency": ("延迟", "一次 request 或一步操作从开始到完成所花的时间"),
    "benchmark": ("基准测试", "在固定条件下测量和比较系统性能"),

    # 07 · vLLM
    "worker": ("工作进程", "实际持有设备并执行模型或数据操作的 process"),
    "executor": ("执行器", "把 scheduler 的计划分发到一个或多个 workers 执行"),
    "metadata": ("元数据", "描述数据身份、布局和执行方式的控制信息"),
    "block": ("块", "KV Cache 等系统中固定粒度的内存管理单位"),
    "block table": ("块表", "把逻辑 KV blocks 映射到物理 block ID"),
    "slot mapping": ("槽位映射", "把本轮 token 映射到具体 KV 写入位置"),
    "eviction": ("淘汰", "回收可丢弃 cache 以腾出资源"),
    "ownership": ("归属关系", "说明某个资源当前由哪个 request、rank 或组件持有"),

    # 08 · KV Connector / NIXL
    "producer": ("生产端", "产生并提供 KV state 的一侧"),
    "consumer": ("消费端", "接收 KV 并继续使用它的一侧"),
    "control plane": ("控制面", "负责 scheduler、状态和传输计划等控制信息"),
    "data plane": ("数据面", "负责真正的大块 KV 数据移动"),
    "transfer": ("传输", "把数据从一个位置移动到另一个位置"),
    "handoff": ("交接", "把已有 KV state 转移给另一个实例继续使用"),
    "descriptor": ("描述符", "描述一段可传输内存位置和属性的结构"),
    "region": ("内存区域", "传输层注册或操作的一段内存范围"),
    "lease": ("租约", "在有效期内保证远端资源继续保留的生命周期机制"),
    "heartbeat": ("心跳", "周期性证明 consumer 仍存活并维持资源有效期的消息"),
    "completion": ("完成状态", "表示异步操作已经安全结束的确认"),
    "peer": ("对端", "通信或 transfer 中的另一侧 process 或实例"),
}

# Exact identifiers are preserved verbatim; the surrounding prose explains them.
IDENTIFIER_ALLOWLIST = {
    "ColumnParallelLinear", "RowParallelLinear", "SchedulerOutput",
    "ModelRunnerOutput", "KVCacheManager", "BlockPool", "KVCacheBlock",
    "EngineCore", "RequestStatus", "InputBatch", "BlockTable", "BlockTables",
    "ModelRunner", "GPUModelRunner",
}
